### ISSUE TITLE
TypeError: Cannot read property 'login' of null

### ISSUE THREAD

**Issue by valasek** [yusufkandemir/quasarian-in-action-helper#14]
@yusufkandemir can you please have a look and maybe just share a quick fix so I can generate weekly news this week?

**Error log:**
> valasek:~/Programming/tmp/quasarian-in-action-helper$ ./bin/parse-issues > quasarian-weekly.json
> Full details:
> TypeError: Cannot read property 'login' of null
>     at /home/valasek/Programming/tmp/quasarian-in-action-helper/src/parse.js:139:67
>     at Array.filter (<anonymous>)
>     at parseCommitCounts (/home/valasek/Programming/tmp/quasarian-in-action-helper/src/parse.js:139:6)
>     at processTicksAndRejections (internal/process/task_queues.js:94:5)
>     at async /home/valasek/Programming/tmp/quasarian-in-action-helper/src/cli.js:35:25
>     at async /home/valasek/Programming/tmp/quasarian-in-action-helper/src/cli.js:30:28
>     at async /home/valasek/Programming/tmp/quasarian-in-action-helper/src/cli.js:30:28
>     at async /home/valasek/Programming/tmp/quasarian-in-action-helper/src/cli.js:30:28
>     at async /home/valasek/Programming/tmp/quasarian-in-action-helper/src/cli.js:30:28
>     at async /home/valasek/Programming/tmp/quasarian-in-action-helper/src/cli.js:30:28
> 
> Short explanation:
> Cannot read property 'login' of null

**Comment by yusufkandemir** [comment]
@valasek the issue is happening in https://github.com/yusufkandemir/quasarian-in-action-helper/blob/bc61ab6f7f5c7fcec26c13859737aa9d94c64f6d/src/parse.js#L138-L140
which means `commit.author` can be `null`, I couldn't find any mention to this in Github API docs. After some research, I found this issue https://github.com/octokit/rest.js/issues/1418#issuecomment-508423767.

So we can either discard the results that have no authors(the ones that probably deleted their accounts) or make them count as `[others]`. What is your opinion on this?

**Comment by valasek** [comment]
Please add it to others

**Comment by valasek** [comment]
Thank you, works and the error does not block processing. PR can be merged and issue closed.
